name: First Workflow
on: push

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: echo a name
        run: echo "I am from GitHub Actions"
      - name: multiline script
        run: |-
          echo "Prints"
          echo "in multiple lines"